### ISSUE TITLE
Classes across modules seem to become null

### ISSUE THREAD

**Issue by avivbeeri** [wren-lang/wren#608]
Ran across this error when I embedded the VM in my game engine, but it shows up in the standalone VM also.

I have three files, like this:
main.wren
```
import "./state" for State

class Game {
  static init() {
    __state = State.new("start")
  }
  static update() {
    if (__state.next) {
      __state = __state.next
    }
    __state.update("word")
  }
}

Game.init()
while (true) {
  Game.update()
}
```

state.wren
```
import "./badstate" for BadState

class State {
  construct new(message) {
    System.print("new state")
    _text = message
  }

  update(m) {
    if (m) {
      next = BadState.new(m)
    }
  }

  text { _text }
  next { _next }
  next=(v) { _next = v }
}
```

and badstate.wren:
```
import "./state" for State

class BadState {

  construct new(message) {
    System.print("bad state")
    _text = message
  }

  update(m) {
    if (m) {
      next = State.new(m)
    }
  }

  text { "Dumb" }
  next { _next }
  next=(v) { _next = v }
}
```

It produces the following output:
```
❯ ./wren main.wren
new state
bad state
Null does not implement 'new(_)'.
[./badstate line 12] in update(_)
[./main line 11] in update()
[./main line 17] in (script)
```

Where as I would expect it to flipflop between `new state` and `bad state` forever. Any ideas?

EDIT: This doesn't happen if all the classes are in the same file/module.

**Comment by mhermier** [comment]
This is a cross reference evaluation.
One of the script evaluate before the other resulting in an import being
resolved to null.

Not sure if it will work but try to put imports at the end of the script
instead. Not sure if it will solve the issue in all the cases, but it
should open a window to late resolve the name to a correct value.

**Comment by avivbeeri** [comment]
Putting the import at the end of state.wren solves the issue. That is hugely unintuitive though. You usually expect imports to be at the top of a piece of code, although I know Wren can scope them.

**Comment by avivbeeri** [comment]
I'm wondering if there is a better way to mitigate this issue, as I'm so used to importing things at the start of a module or script, across several languages.

**Comment by mhermier** [comment]
I think that an even more idiomatic way would be to get the class via a
Singleton like getter method.

**Comment by avivbeeri** [comment]
How would that help though? You'd still have issues with cyclic imports if
you weren't careful...

**Comment by mhermier** [comment]
You didn't understood what I meant.

I meant something like this:
```

class State {
  construct new(message) {
    System.print("new state")
    _text = message
  }

  badStateClass {

    if (!_badStateClass) {

      import "./badstate" for BadState

      _badStateClass = BadState

    }

    return _badStateClass

  }


  update(m) {
    if (m) {
      next = badStateClass.new(m)
    }
  }

  text { _text }
  next { _next }
  next=(v) { _next = v }
}

```

**Comment by munificent** [comment]
Yeah, this is working as intended, though I agree it's confusing if you are coming from some other languages. In general, there is a split in languages for what the top level of a file means. In statically typed languages like C, Java, C#, etc. the top level is purely a collection of declarations. It's easy to resolve cyclic imports because you can traverse the entire import graph and build up all the declarations before you execute *any* code.

In scripting languages, the top level of a script is imperative code. That means an import may have user-visible side effects. In fact, the import itself may be executed dynamically. Wren, like other scripting languages, doesn't even prevent you from building the module string you are importing dynamically. That means an import really needs to be executed at the moment that you reach it.

That makes cyclic imports and cyclic references between modules harder. You can usually work around it by rearranging your code. Yes, sometimes it means putting the import later in the file or inside a block of code. That's idiomatic in Python and Ruby too.

I think the problem feels worse in Wren because Wren tries hard to look like an object oriented language and the top level does seem more declarative than it really is.

**Comment by mhermier** [comment]
I wonder how costly it would be to have a *statically* compiled version of
the language? Basically in the compiler, it should be a few (2 or little
more) rules too changes. But to have proper linking it would require either
another compiler or some fine trickery, like an unresolved reference object.
